### ISSUE TITLE
No prediction output when using macrel reads

### ISSUE THREAD

**Issue by karindadelacruz** [BigDataBiology/macrel#65] opened 2023-10-25 14:10 UTC
I have been testing out the functions of macrel with some of my own data. I used the contigs subcommand without issues and  produce all expected files. I used some metagenomic data to run the reads subcommand and have been not receiving the AMP prediction output from any of the sequences I have tested. 

From this I decided to use the test files that you provide to run the reads subcommand to see if I can reproduce all of the correct files. However I am also not receiving the expected macrel.out.prediction.gz file that is associated with the test reads that you provide. 

Here is the code that I am using to produce the data:
`macrel reads -1 ./test_reads_data/R1.fq.gz -2 ./test_reads_data/R2.fq.gz --output expected_output`

From this code I am able to receive macrel.out.all_orfs.faa and and macrel.out.smorfs.faa but I never produce the macrel.out.prediction.gz file with the reads subcommand for any input data I have used.

**Comment by celiosantosjr** [comment] 2023-10-30 20:52
Dear Karinda, 

For the most, we could not reproduce your error. We only can suppose that is something related to the 
version of packages in your environment conflicting internally in Macrel. 

We refactored the bioconda recipe for Macrel (build 1) to deliberately directs the system to install the
compatible packages, such as python version 3.10, scikit-learn library and others. It was also updated
in the installation script in the git repository the versions for the programs used in the system to keep
compatibility with older python versions. 

Our suggestion to avoid any incompatibility due to execution in different environments is installing
Macrel in its dedicated environment.

You can do that by using mamba:

```
mamba create --name macrel_env -c bioconda macrel
conda activate macrel_env
macrel -h
```

Or by using conda, which may take a bit longer with the same result:

```
conda create --name env_macrel -c bioconda macrel
conda activate macrel_env
macrel -h
```
Let us know if the problem persists.

Best,
Celio

**Comment by karindadelacruz** [comment] 2023-11-01 10:33
Hello,

I tried installing macrel into its own dedicated environment as suggested and it no longer installs using conda. It gets stuck at "solving environments" for hours. I had someone else try to install in the recommended way and the installation also gets stuck at that same point. Thus, I am unable to test if it works on paired-end reads using this updated version. 

Thanks for the help,

Karinda

**Comment by celiosantosjr** [comment] 2023-11-03 13:25
Dear Karinda,

I am sorry for not being able to help much, since I cannot reproduce your
error. After updating the recipe, I tested the system using it locally and
in a server and both does seem to work using conda and mamba, although in
fact the first takes a long time.

The suggestion I have is for you to either try using Mamba (which reduces
considerably the time of installation) or installing it from the source in
GitHub.

I am closing this issue now as I cannot help much more than that. If you
persist the error or need anything new you also can email the google group
of AMPSphere-users <https://groups.google.com/g/ampsphere-users?pli=1>.

Best

**Closed** 2023-11-03 13:26 UTC
